/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import Controller.Abrir;
import javax.swing.UIManager;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import modelo.Aluno;

/**
 *
 * @author Matheus LK Arthur Bolsoni
 * @since 4/07/2017 - 16:00
 * @version 1.5 Beta maisamornocoraçãothiago
 */
public class Menu extends javax.swing.JFrame implements InternalFrameListener {

    public boolean flagCadAluno = false;
    public boolean flagCadProfessor = false;
    public boolean flagCadTurma = false;
    public boolean flagConfigTurma = false;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setExtendedState(MAXIMIZED_HORIZ);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jAreaTrabalho = new javax.swing.JDesktopPane();
        jmbBarra = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiCadAluno = new javax.swing.JMenuItem();
        jmiCadProfessor = new javax.swing.JMenuItem();
        jmiTurma = new javax.swing.JMenuItem();
        jmTurma = new javax.swing.JMenu();
        jmAluno = new javax.swing.JMenu();
        jmProfessor = new javax.swing.JMenu();
        jmSair = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jAreaTrabalhoLayout = new javax.swing.GroupLayout(jAreaTrabalho);
        jAreaTrabalho.setLayout(jAreaTrabalhoLayout);
        jAreaTrabalhoLayout.setHorizontalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        jAreaTrabalhoLayout.setVerticalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        jmCadastro.setText("Cadastro");
        jmCadastro.setToolTipText("");

        jmiCadAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiCadAluno.setText("Pra Dps");
        jmiCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadAlunoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadAluno);

        jmiCadProfessor.setText("Professor");
        jmiCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadProfessorActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadProfessor);

        jmiTurma.setText("Turma");
        jmiTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTurmaActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiTurma);

        jmbBarra.add(jmCadastro);

        jmTurma.setText("Turma");
        jmTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmTurmaMouseClicked(evt);
            }
        });
        jmbBarra.add(jmTurma);

        jmAluno.setText("Pra Dps");
        jmAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAlunoMouseClicked(evt);
            }
        });
        jmAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlunoActionPerformed(evt);
            }
        });
        jmbBarra.add(jmAluno);

        jmProfessor.setText("Professor");
        jmProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmProfessorMouseClicked(evt);
            }
        });
        jmbBarra.add(jmProfessor);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jmbBarra.add(jmSair);

        setJMenuBar(jmbBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirCadAluno() {
        if (!flagCadAluno) {

            UICadAluno cp = new UICadAluno();
            jAreaTrabalho.add(cp);
            cp.setVisible(true);

            flagCadAluno = true;
            cp.addInternalFrameListener(this);
        }
    }

    private void abrirCadProfessor() {
        if (!flagCadProfessor) {

            UICadProfessor cp = new UICadProfessor();
            jAreaTrabalho.add(cp);
            cp.setVisible(true);

            flagCadProfessor = true;
            cp.addInternalFrameListener(this);
        }
    }

    private void abrirCadTurma() {
        if (!flagCadTurma) {

            UICadTurma cp = new UICadTurma();
            jAreaTrabalho.add(cp);
            cp.setVisible(true);

            flagCadTurma = true;
            cp.addInternalFrameListener(this);
        }
    }

    private void abrirConfigTurma() {

        UIConfigTurma ap = new UIConfigTurma(null, true);
        ap.setVisible(true);
    }

    private void abrirConfigAluno() {

        UIConfigAluno ap = new UIConfigAluno(null, true, null);
        ap.setVisible(true);
    }

    private void abrirSobre() {
        UISobre ap = new UISobre(null, true);
        ap.setVisible(true);
    }

    private void abrirSelecionarProfessor() {
        Abrir ap = new Abrir();
        ap.abrirprofessor(null);
    }

    private void abrirSelecionarAluno() {
        Abrir ap = new Abrir();
        ap.abrirAluno(null);
    }
    private void jmiCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadAlunoActionPerformed
        // TODO add your handling code here:
        abrirCadAluno();
    }//GEN-LAST:event_jmiCadAlunoActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmSairMouseClicked

    private void jmiCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadProfessorActionPerformed
        abrirCadProfessor();
    }//GEN-LAST:event_jmiCadProfessorActionPerformed

    private void jmiTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTurmaActionPerformed
        // TODO add your handling code here:
        abrirCadTurma();
    }//GEN-LAST:event_jmiTurmaActionPerformed

    private void jmTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmTurmaMouseClicked
        abrirConfigTurma();
    }//GEN-LAST:event_jmTurmaMouseClicked

    private void jmAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlunoActionPerformed
        abrirConfigAluno();        // TODO add your handling code here:
    }//GEN-LAST:event_jmAlunoActionPerformed

    private void jmAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAlunoMouseClicked
        // TODO add your handling code here:
        abrirSelecionarAluno();
    }//GEN-LAST:event_jmAlunoMouseClicked

    private void jmProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmProfessorMouseClicked
        abrirSelecionarProfessor();
    }//GEN-LAST:event_jmProfessorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            com.jtattoo.plaf.acryl.AcrylLookAndFeel.setTheme("Green", "INSERT YOUR LICENSE KEY HERE", "my company");
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jmAluno;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmProfessor;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenu jmTurma;
    private javax.swing.JMenuBar jmbBarra;
    private javax.swing.JMenuItem jmiCadAluno;
    private javax.swing.JMenuItem jmiCadProfessor;
    private javax.swing.JMenuItem jmiTurma;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent e) {

    }

    @Override
    public void internalFrameClosing(InternalFrameEvent e) {

    }

    @Override
    public void internalFrameClosed(InternalFrameEvent e) {
        if (e.getInternalFrame() instanceof UICadAluno) {
            flagCadAluno = false;
        }
        if (e.getInternalFrame() instanceof UICadProfessor) {
            flagCadProfessor = false;
        }
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent e) {

    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent e) {

    }

    @Override
    public void internalFrameActivated(InternalFrameEvent e) {

    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent e) {

    }
}
