/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Aluno;
import modelo.Contato;
import modelo.Endereco;
import modelo.Validar;
import servicos.AlunoServicos;
import servicos.ServicoFactory;

/**
 * 
 * @author Matheus LK Arthur Bolsoni
 * @since 4/07/2017 - 16:00
 * @version 1.5 Beta maisamornocoraçãothiago
 */
public class UICadAluno extends javax.swing.JInternalFrame {
    /**
     * Creates new form UICadPessoa
     */
    public UICadAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jtEmail = new javax.swing.JTextField();
        jtTelefone = new javax.swing.JTextField();
        jtCelular = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jlCelularErro = new javax.swing.JLabel();
        jlTelefoneErro = new javax.swing.JLabel();
        jlEmailErro = new javax.swing.JLabel();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jtCep = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jtRua = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jtBairro = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jtCidade = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jtNumero = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jlCidadeErro = new javax.swing.JLabel();
        jlBairroErro = new javax.swing.JLabel();
        jlRuaErro = new javax.swing.JLabel();
        jlNumErro = new javax.swing.JLabel();
        jlCepErro = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jrbFeminino = new javax.swing.JRadioButton();
        jtClasseSocial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtNascimento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNascionalidade = new javax.swing.JTextField();
        jtCor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jrbMasculino = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtCpf = new javax.swing.JTextField();
        jtRg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtCidadeOrigem = new javax.swing.JTextField();
        jlNomeErro = new javax.swing.JLabel();
        jlCpfErro = new javax.swing.JLabel();
        jlRGErro = new javax.swing.JLabel();
        jlDN = new javax.swing.JLabel();
        jlCLErro = new javax.swing.JLabel();
        jlCorErro = new javax.swing.JLabel();
        jlNacionalidadeErro = new javax.swing.JLabel();
        jlCOErro = new javax.swing.JLabel();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        jbCadastrar4 = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Aluno");
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(0, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));

        jtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtEmailFocusLost(evt);
            }
        });
        jtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmailActionPerformed(evt);
            }
        });

        jtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtTelefoneFocusLost(evt);
            }
        });
        jtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTelefoneActionPerformed(evt);
            }
        });

        jtCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCelularFocusLost(evt);
            }
        });
        jtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCelularActionPerformed(evt);
            }
        });

        jLabel31.setText("Celular:");

        jLabel32.setText("E-mail:");

        jLabel33.setText("Telefone:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtEmail))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtTelefone)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCelularErro)
                    .addComponent(jlTelefoneErro)
                    .addComponent(jlEmailErro))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jlCelularErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTelefoneErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jlEmailErro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane6.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jtCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCepFocusLost(evt);
            }
        });
        jtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCepActionPerformed(evt);
            }
        });

        jLabel26.setText("CEP:");

        jtRua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtRuaFocusLost(evt);
            }
        });
        jtRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRuaActionPerformed(evt);
            }
        });

        jLabel27.setText("Rua");

        jtBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtBairroFocusLost(evt);
            }
        });
        jtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBairroActionPerformed(evt);
            }
        });

        jLabel28.setText("Bairro");

        jtCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCidadeFocusLost(evt);
            }
        });

        jLabel29.setText("Cidade:");

        jtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNumeroFocusLost(evt);
            }
        });
        jtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNumeroActionPerformed(evt);
            }
        });

        jLabel30.setText("Numero");

        jLayeredPane6.setLayer(jtCep, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jtRua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jtBairro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jtCidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jtNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jlCidadeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jlBairroErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jlRuaErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jlNumErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jlCepErro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCep))
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNumero))
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtRua))
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtBairro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jlNumErro))
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCidadeErro)
                            .addComponent(jlBairroErro)
                            .addComponent(jlRuaErro)
                            .addComponent(jlCepErro))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCidadeErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlBairroErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlRuaErro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jlNumErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jlCepErro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de aluno"));

        bgSexo.add(jrbFeminino);
        jrbFeminino.setText("Feminino");
        jrbFeminino.setActionCommand("Feminino");
        jrbFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFemininoActionPerformed(evt);
            }
        });
        jrbFeminino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbFemininoKeyPressed(evt);
            }
        });

        jtClasseSocial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtClasseSocialFocusLost(evt);
            }
        });
        jtClasseSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtClasseSocialActionPerformed(evt);
            }
        });
        jtClasseSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtClasseSocialKeyPressed(evt);
            }
        });

        jLabel7.setText("Classe social:");

        jLabel3.setText("Data de nascimento");

        jtNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNascimentoFocusLost(evt);
            }
        });
        jtNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNascimentoActionPerformed(evt);
            }
        });

        jLabel9.setText("Cor:");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeActionPerformed(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Nascionalidade:");

        jtNascionalidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNascionalidadeFocusLost(evt);
            }
        });
        jtNascionalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNascionalidadeKeyPressed(evt);
            }
        });

        jtCor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCorFocusLost(evt);
            }
        });

        jLabel10.setText("Sexo:");

        bgSexo.add(jrbMasculino);
        jrbMasculino.setText("Masculino");
        jrbMasculino.setActionCommand("Masculino");
        jrbMasculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbMasculinoKeyPressed(evt);
            }
        });

        jLabel4.setText("Ex: 10/10/2010");

        jLabel5.setText("CPF:");

        jLabel11.setText("RG:");

        jtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCpfFocusLost(evt);
            }
        });

        jtRg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtRgFocusLost(evt);
            }
        });

        jLabel8.setText("Cidade de origem:");

        jtCidadeOrigem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCidadeOrigemFocusLost(evt);
            }
        });
        jtCidadeOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCidadeOrigemActionPerformed(evt);
            }
        });
        jtCidadeOrigem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCidadeOrigemKeyPressed(evt);
            }
        });

        jLayeredPane3.setLayer(jrbFeminino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jtClasseSocial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jtNascimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jtNascionalidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jtCor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jrbMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jtCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jtRg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jtCidadeOrigem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jlCpfErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jlRGErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jlDN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jlCLErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jlCorErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jlNacionalidadeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jlCOErro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbMasculino, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jrbFeminino)))
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jlCorErro))))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtRg))
                                        .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addComponent(jlCpfErro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlNomeErro))
                                    .addComponent(jlRGErro)))
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtNascionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlNacionalidadeErro))
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtCidadeOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtClasseSocial))
                                        .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlDN)
                                    .addComponent(jlCLErro)
                                    .addComponent(jlCOErro))))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNomeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCpfErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlRGErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDN))
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtClasseSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCLErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCorErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jrbFeminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMasculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNascionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNacionalidadeErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCidadeOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCOErro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane7.setBorder(javax.swing.BorderFactory.createTitledBorder("Conclusão"));

        jbCadastrar4.setText("Concluir");
        jbCadastrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrar4ActionPerformed(evt);
            }
        });

        jLayeredPane7.setLayer(jbCadastrar4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane7Layout = new javax.swing.GroupLayout(jLayeredPane7);
        jLayeredPane7.setLayout(jLayeredPane7Layout);
        jLayeredPane7Layout.setHorizontalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jbCadastrar4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane7Layout.setVerticalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbCadastrar4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEmailFocusLost
        // TODO add your handling code here:
        if(!Validar.validarEmail(jtEmail.getText())){
            jtEmail.setBorder(BorderFactory.createLineBorder(Color.red));
            jlEmailErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtEmail.setBorder(BorderFactory.createLineBorder(Color.green));
            jlEmailErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtEmailFocusLost

    private void jtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmailActionPerformed

    private void jtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTelefoneFocusLost
        // TODO add your handling code here:
        if(!Validar.validarNumero(jtTelefone.getText())){
            jtTelefone.setBorder(BorderFactory.createLineBorder(Color.red));
            jlTelefoneErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtTelefone.setBorder(BorderFactory.createLineBorder(Color.green));
            jlTelefoneErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtTelefoneFocusLost

    private void jtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTelefoneActionPerformed

    private void jtCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCelularFocusLost
        // TODO add your handling code here:
        if(!Validar.validarNumero(jtCelular.getText())){
            jtCelular.setBorder(BorderFactory.createLineBorder(Color.red));
            jlCelularErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtCelular.setBorder(BorderFactory.createLineBorder(Color.green));
            jlCelularErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtCelularFocusLost

    private void jtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCelularActionPerformed

    private void jtCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCepFocusLost
        // TODO add your handling code here:
        if(!Validar.validarNumero(jtCep.getText())){
            jtCep.setBorder(BorderFactory.createLineBorder(Color.red));
            jlCepErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtCep.setBorder(BorderFactory.createLineBorder(Color.green));
            jlCpfErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtCepFocusLost

    private void jtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCepActionPerformed

    private void jtRuaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtRuaFocusLost
        // TODO add your handling code here:
        if(!Validar.validarNome(jtRua.getText())){
            jtRua.setBorder(BorderFactory.createLineBorder(Color.red));
            jlRuaErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtRua.setBorder(BorderFactory.createLineBorder(Color.green));
            jlRuaErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtRuaFocusLost

    private void jtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRuaActionPerformed

    private void jtBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtBairroFocusLost
        // TODO add your handling code here:
        if(!Validar.validarNome(jtBairro.getText())){
            jtBairro.setBorder(BorderFactory.createLineBorder(Color.red));
            jlBairroErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtBairro.setBorder(BorderFactory.createLineBorder(Color.green));
            jlBairroErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtBairroFocusLost

    private void jtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBairroActionPerformed

    private void jtCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCidadeFocusLost
        // TODO add your handling code here:
        if(!Validar.validarNome(jtCidade.getText())){
            jtCidade.setBorder(BorderFactory.createLineBorder(Color.red));
            jlCidadeErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtCidade.setBorder(BorderFactory.createLineBorder(Color.green));
            jlCidadeErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtCidadeFocusLost

    private void jtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumeroFocusLost
        // TODO add your handling code here:
        if(!Validar.validarNumero(jtNumero.getText())){
            jtNumero.setBorder(BorderFactory.createLineBorder(Color.red));
            jlNumErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtNumero.setBorder(BorderFactory.createLineBorder(Color.green));
            jlNumErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtNumeroFocusLost

    private void jtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNumeroActionPerformed

    private void jrbFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbFemininoActionPerformed

    private void jrbFemininoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbFemininoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbFemininoKeyPressed

    private void jtClasseSocialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtClasseSocialFocusLost
        if(!Validar.validarNome(jtClasseSocial.getText())){
            jtClasseSocial.setBorder(BorderFactory.createLineBorder(Color.red));
            jlCLErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtClasseSocial.setBorder(BorderFactory.createLineBorder(Color.green));
            jlCLErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtClasseSocialFocusLost

    private void jtClasseSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtClasseSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtClasseSocialActionPerformed

    private void jtClasseSocialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtClasseSocialKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtClasseSocialKeyPressed

    private void jtNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNascimentoFocusLost
        // TODO add your handling code here:
        if(!Validar.validarData(jtNascimento.getText())){
            jtNascimento.setBorder(BorderFactory.createLineBorder(Color.red));
            jlDN.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtNascimento.setBorder(BorderFactory.createLineBorder(Color.green));
            jlDN.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtNascimentoFocusLost

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        if(!Validar.validarNome(jtNome.getText())){
            jtNome.setBorder(BorderFactory.createLineBorder(Color.red));
            jlNomeErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtNome.setBorder(BorderFactory.createLineBorder(Color.green));
            jlNomeErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeActionPerformed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtNascionalidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNascionalidadeFocusLost
        if(!Validar.validarNome(jtNascionalidade.getText())){
            jtNascionalidade.setBorder(BorderFactory.createLineBorder(Color.red));
            jlNacionalidadeErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtNascionalidade.setBorder(BorderFactory.createLineBorder(Color.green));
            jlNacionalidadeErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtNascionalidadeFocusLost

    private void jtNascionalidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNascionalidadeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNascionalidadeKeyPressed

    private void jtCorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCorFocusLost
        // TODO add your handling code here:
        if(!Validar.validarNome(jtCor.getText())){
            jtCor.setBorder(BorderFactory.createLineBorder(Color.red));
            jlCorErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtCor.setBorder(BorderFactory.createLineBorder(Color.green));
            jlCorErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtCorFocusLost

    private void jrbMasculinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbMasculinoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMasculinoKeyPressed

    private void jtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCpfFocusLost
        // TODO add your handling code here:
        if(!Validar.validarcpf(jtCpf.getText())){
            jtCpf.setBorder(BorderFactory.createLineBorder(Color.red));
            jlCpfErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtCpf.setBorder(BorderFactory.createLineBorder(Color.green));
            jlCpfErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtCpfFocusLost

    private void jtRgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtRgFocusLost
        // TODO add your handling code here:
        if(!Validar.validarNumero(jtRg.getText())){
            jtRg.setBorder(BorderFactory.createLineBorder(Color.red));
            jlRGErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtRg.setBorder(BorderFactory.createLineBorder(Color.green));
            jlRGErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtRgFocusLost

    private void jtCidadeOrigemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCidadeOrigemFocusLost
        // TODO add your handling code here:
        if(!Validar.validarNome(jtCidadeOrigem.getText())){
            jtCidadeOrigem.setBorder(BorderFactory.createLineBorder(Color.red));
            jlCOErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/error.png")));
        }else{
            jtCidadeOrigem.setBorder(BorderFactory.createLineBorder(Color.green));
            jlCOErro.setIcon(
                new ImageIcon(
                    getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtCidadeOrigemFocusLost

    private void jtCidadeOrigemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCidadeOrigemKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCidadeOrigemKeyPressed

    private void jbCadastrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrar4ActionPerformed
        // TODO add your handling code here:
        cadastrar();
    }//GEN-LAST:event_jbCadastrar4ActionPerformed

    private void jtNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNascimentoActionPerformed

    private void jtCidadeOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCidadeOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCidadeOrigemActionPerformed
    public void cadastrar(){
        try {
         
        Aluno aluno = new Aluno();
        //Nome
        if (Validar.validarNome(jtNome.getText())) {
                aluno.setNome(jtNome.getText());
            } else {
                throw new NumberFormatException("Digite o nome!");
            }
        //CPF
        if (Validar.validarcpf(jtCpf.getText())) {
                aluno.setClasseSocial(jtCpf.getText());
            } else {
                throw new NumberFormatException("Digite um cpf valido!");
            }
        //RG
        if (Validar.validarNumero(jtRg.getText())) {
                aluno.setRg(jtRg.getText());
            } else {
                throw new NumberFormatException("Digite um RG!");
            }
        
            //Idade
            DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            try {
                LocalDate d = LocalDate.parse(jtNascimento.getText(), formatador);
                d.format(formatador);
                aluno.setDataNascimento(d);
            } catch (Exception e) {
                throw new Exception("Selecione a data corretamente! " + e.getMessage());
            }
            
        //Classe social
        if (Validar.validarNome(jtClasseSocial.getText())) {
                aluno.setClasseSocial(jtClasseSocial.getText());
            } else {
                throw new NumberFormatException("Digite a classe social!");
            }
        
        //Cor
        if (Validar.validarNome(jtCor.getText())) {
                aluno.setCor(jtCor.getText());
            } else {
                throw new NumberFormatException("Digite a cor!");
            }
        //Sexo
        if (jrbFeminino.isSelected() || jrbMasculino.isSelected()) {
                    aluno.setSexo(bgSexo.getSelection().getActionCommand());
            } else {
                throw new Exception("Selecione o sexo!");
            }
        //Nacionalidade
        if (Validar.validarNome(jtNascionalidade.getText())) {
                aluno.setNascionalidade(jtNascionalidade.getText());
            } else {
                throw new NumberFormatException("Digite a nascionalidade!");
            }
        //Cidade de origem
        if (Validar.validarNome(jtCidadeOrigem.getText())) {
                aluno.setCidadeOrigem(jtCidadeOrigem.getText());
            } else {
                throw new NumberFormatException("Digite a cidade de origem!");
            }
            
            
            //Endereço
            
            
            Endereco endereco = new Endereco();
            //Cidade
            if (Validar.validarNome(jtCidade.getText())) {
                endereco.setCidade(jtCidade.getText());
            } else {
                throw new NumberFormatException("Digite a cidade! ");
            }
            //Bairro
            if (Validar.validarNome(jtBairro.getText())) {
                endereco.setBairro(jtBairro.getText());
            } else {
                throw new NumberFormatException("Digite o bairro! ");
            }
            //Rua
            if (Validar.validarNome(jtRua.getText())) {
                endereco.setRua(jtRua.getText());
            } else {
                throw new NumberFormatException("Digite a rua!");
            }
            //Numero
            if (Validar.validarNumero(jtNumero.getText())) {
                endereco.setNumeroCasa(Integer.parseInt(jtNumero.getText()));
            } else {
                throw new NumberFormatException("Digite o numero!");
            }
            //CEP
            if (Validar.validarNumero(jtCep.getText())) {
                endereco.setCep(jtCep.getText());
            } else {
                throw new NumberFormatException("Digite o cep!");
            }
            
            //Contato
            
            
            Contato contato = new Contato();
            
            //Celular
            if (Validar.validarNumero(jtCelular.getText())) {
                contato.setCelular(jtCelular.getText());
            } else {
                throw new NumberFormatException("Digite o celular!");
            }
            //Telefone
            if (Validar.validarNumero(jtTelefone.getText())) {
                contato.setTelefone(jtTelefone.getText());
            } else {
                throw new NumberFormatException("Digite o telefone!");
            }
            //Email
            if (Validar.validarEmail(jtEmail.getText())) {
                contato.setEmail(jtEmail.getText());
            } else {
                throw new NumberFormatException("Digite o email!");
            }
            
            aluno.setEndereco(endereco);
            aluno.setContato(contato);
            
       AlunoServicos c = ServicoFactory.getAluno();
        
        c.cadastrar(aluno);
        
        JOptionPane.showMessageDialog(
                    rootPane, 
                    "Aluno cadastrada com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! "+e.getMessage(),
                    "erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbCadastrar4;
    private javax.swing.JLabel jlBairroErro;
    private javax.swing.JLabel jlCLErro;
    private javax.swing.JLabel jlCOErro;
    private javax.swing.JLabel jlCelularErro;
    private javax.swing.JLabel jlCepErro;
    private javax.swing.JLabel jlCidadeErro;
    private javax.swing.JLabel jlCorErro;
    private javax.swing.JLabel jlCpfErro;
    private javax.swing.JLabel jlDN;
    private javax.swing.JLabel jlEmailErro;
    private javax.swing.JLabel jlNacionalidadeErro;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlNumErro;
    private javax.swing.JLabel jlRGErro;
    private javax.swing.JLabel jlRuaErro;
    private javax.swing.JLabel jlTelefoneErro;
    private javax.swing.JRadioButton jrbFeminino;
    private javax.swing.JRadioButton jrbMasculino;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtCelular;
    private javax.swing.JTextField jtCep;
    private javax.swing.JTextField jtCidade;
    private javax.swing.JTextField jtCidadeOrigem;
    private javax.swing.JTextField jtClasseSocial;
    private javax.swing.JTextField jtCor;
    private javax.swing.JTextField jtCpf;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtNascimento;
    private javax.swing.JTextField jtNascionalidade;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumero;
    private javax.swing.JTextField jtRg;
    private javax.swing.JTextField jtRua;
    private javax.swing.JTextField jtTelefone;
    // End of variables declaration//GEN-END:variables
}
