/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import Controller.Abrir;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import servicos.TurmaServicos;
import servicos.ServicoFactory;
import modelo.Aluno;
import modelo.Horario;
import modelo.Turma;
import servicos.AlunoServicos;
import servicos.HorarioServicos;
import sun.misc.VM;

/**
 *
 * @author admin
 */
public class UIConfigTurma extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"segunda", "terça", "quarta", "quinta", "sexta", "sabado"});

    /**
     * Creates new form UIConfigTurma
     */
    public UIConfigTurma(java.awt.Frame parent, boolean modal) {

        initComponents();
        preencherListaAluno();
        preencherListaTurma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListTurmas = new javax.swing.JList();
        jtFiltrarTurma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPeriodos = new javax.swing.JTable();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListAlunos = new javax.swing.JList();
        jtFiltrarAluno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JComboTurmas = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTodosOsAlunos = new javax.swing.JList();
        jToggleButton1 = new javax.swing.JToggleButton();

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de turmas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11))); // NOI18N

        jListTurmas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jListTurmas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListTurmasValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jListTurmas);

        jtFiltrarTurma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtFiltrarTurmaKeyReleased(evt);
            }
        });

        jLabel3.setText("Pesquisar:");

        jLayeredPane1.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtFiltrarTurma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtFiltrarTurma)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtFiltrarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Periodos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11))); // NOI18N

        jtPeriodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"
            }
        ));
        jScrollPane1.setViewportView(jtPeriodos);

        jLayeredPane3.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
        );

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de alunos"));

        jListAlunos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jListAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListAlunosMouseClicked(evt);
            }
        });
        jListAlunos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListAlunosValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(jListAlunos);

        jtFiltrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFiltrarAlunoActionPerformed(evt);
            }
        });
        jtFiltrarAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtFiltrarAlunoKeyReleased(evt);
            }
        });

        jLabel1.setText("Pesquisar:");

        jLayeredPane4.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtFiltrarAluno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtFiltrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtFiltrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar alunos a turma"));

        jLabel2.setText("Turma:");

        jScrollPane2.setViewportView(jListTodosOsAlunos);

        jToggleButton1.setText("Adicionar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JComboTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JComboTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane4)
                            .addComponent(jLayeredPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtFiltrarAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtFiltrarAlunoKeyReleased
        // TODO add your handling code here:
        filtrarAlunos();
    }//GEN-LAST:event_jtFiltrarAlunoKeyReleased

    private void jtFiltrarTurmaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtFiltrarTurmaKeyReleased
        // TODO add your handling code here:
        filtrarTurmas();
    }//GEN-LAST:event_jtFiltrarTurmaKeyReleased

    private void jtFiltrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFiltrarAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFiltrarAlunoActionPerformed

    private void jListTurmasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTurmasValueChanged
        // TODO add your handling code here:
        limparAlunos();
        filtrarAlunosDaTurma();
        preencherListaPeriodos();
    }//GEN-LAST:event_jListTurmasValueChanged

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        adicinarAlunoTurma();
        preencherListaAluno();
        filtrarAlunosDaTurma();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jListAlunosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListAlunosValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jListAlunosValueChanged

    private void jListAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListAlunosMouseClicked
        // TODO add your handling code here:
        abrirConfigAluno();
        jListAlunos.clearSelection();
    }//GEN-LAST:event_jListAlunosMouseClicked

    private void abrirConfigAluno() {

        Aluno aluno = new Aluno();
        aluno = ((Aluno) jListAlunos.getSelectedValue());

        Abrir ap = new Abrir();
        try {

            ap.abrirAluno(aluno);
        } catch (Exception e) {
        }
    }

    private void filtrarAlunosDaTurma() {
        try {
            if (!jListTurmas.getSelectedValue().toString().isEmpty()) {

                Turma turma = new Turma();
                turma = ((Turma) jListTurmas.getSelectedValue());

                String query = "aluno as a inner join contato as c inner join endereco as e inner join turma as t on "
                        + "a.idcontato = c.idcontato "
                        + "and "
                        + "a.idendereco = e.idendereco "
                        + "and "
                        + "a.idturma = t.idturma "
                        + "where a.idturma = " + turma.getIdTurma();

                ArrayList<Aluno> aluno = new ArrayList<>();
                AlunoServicos a = ServicoFactory.getAluno();

                aluno = a.buscarAluno(query);

                System.out.println(aluno);
                DefaultListModel dlm = new DefaultListModel();

                for (int i = 0; i < aluno.size(); i++) {
                    dlm.addElement(aluno.get(i));
                }
                jListAlunos.setModel(dlm);
            } else {
                preencherListaAluno();
            }
        } catch (Exception e) {
        }
    }

    private void filtrarAlunos() {
        try {
            if (!jtFiltrarAluno.getText().isEmpty()) {
                String filtro = jtFiltrarAluno.getText();

                Turma turma = new Turma();
                turma = ((Turma) jListTurmas.getSelectedValue());

                if (turma != null) {

                    String query = "aluno as a inner join contato as c inner join endereco as e inner join turma as t on "
                            + "a.idcontato = c.idcontato "
                            + "and "
                            + "a.idendereco = e.idendereco "
                            + "and "
                            + "a.idturma = t.idturma "
                            + "where a.idturma = " + turma.getIdTurma()
                            + " and a.nome like '%" + filtro + "%'";

                    ArrayList<Aluno> aluno = new ArrayList<>();
                    AlunoServicos a = ServicoFactory.getAluno();

                    aluno = a.buscarAluno(query);

                    DefaultListModel dlm = new DefaultListModel();

                    for (int i = 0; i < aluno.size(); i++) {
                        dlm.addElement(aluno.get(i));
                    }

                    jListAlunos.setModel(dlm);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao filtrar alunos! " + e.getMessage());
        }
    }

    private void filtrarTurmas() {
        try {
            if (!jtFiltrarTurma.getText().isEmpty()) {
                String filtro = jtFiltrarTurma.getText();

                String query = "turma where turma.numero like '%" + filtro + "%'";

                ArrayList<Turma> turma = new ArrayList<>();
                TurmaServicos a = ServicoFactory.getTurma();

                turma = a.buscarTurmas(query);

                if (!(turma.isEmpty())) {
                    System.out.println(turma);
                    DefaultListModel dlm = new DefaultListModel();

                    for (int i = 0; i < turma.size(); i++) {
                        dlm.addElement(turma.get(i));
                    }
                    jListTurmas.setModel(dlm);
                }
            } else {
                preencherListaTurma();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao filtrar turmas! " + e.getMessage());
        }
    }

    private void limparAlunos() {

        jListAlunos.setModel(new DefaultListModel());
    }

    private void limparTumas() {
        jListTurmas.setModel(new DefaultListModel());
    }

    private void limparTodosAlunos() {
        jListTodosOsAlunos.setModel(new DefaultListModel());
    }

    private void limparTabelaHorario() {
        dtm.setNumRows(0);
    }

    private void preencherListaTurma() {
        try {
            ArrayList<Turma> turma = new ArrayList<>();
            TurmaServicos ss = ServicoFactory.getTurma();

            turma = ss.buscarTurmas("turma");

            if (turma != null) {
                DefaultListModel dlm = new DefaultListModel();
                for (int i = 0; i < turma.size(); i++) {
                    dlm.addElement(turma.get(i));
                    JComboTurmas.addItem(turma.get(i));
                }

                jListTurmas.setModel(dlm);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao preencher lista de turmas! " + e.getMessage());
        }
    }

    private void preencherListaAluno() {
        try {
            ArrayList<Aluno> aluno = new ArrayList<>();
            AlunoServicos ss = ServicoFactory.getAluno();

            aluno = ss.buscarAlunoSemTurma("aluno as a inner join contato as c inner join endereco as e on "
                    + "a.idcontato = c.idcontato "
                    + "and "
                    + "a.idendereco = e.idendereco ");

            DefaultListModel dlm = new DefaultListModel();
            for (int i = 0; i < aluno.size(); i++) {
                dlm.addElement(aluno.get(i));
            }

            jListTodosOsAlunos.setModel(dlm);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao preencher lista de alunos! " + e.getMessage());
        }
    }

    private void preencherListaPeriodos() {
        try {
            ArrayList<Horario> horario = new ArrayList<>();
            HorarioServicos ss = ServicoFactory.getHorario();

            Turma turma = (Turma) jListTurmas.getSelectedValue();

            if (turma != null) {
                horario = ss.buscarHorario("horario as h inner join materia as m inner join turma as t on "
                        + "h.idmateria = m.idmateria "
                        + "and "
                        + "h.idturma = t.idturma "
                        + "where t.numero = " + turma.getNumero());

                limparTabelaHorario();

                for (int i = 0; i < 6; i++) {
                    dtm.addRow(new String[]{});

                    String nome = horario.get(i).getMateria().getNome();

                    dtm.setValueAt(nome, i, 0);

                }//fecha for
                for (int i = 0; i < 6; i++) {

                    String nome = horario.get(i + 6).getMateria().getNome();

                    dtm.setValueAt(nome, i, 1);

                }//fecha for
                for (int i = 0; i < 6; i++) {

                    String nome = horario.get(i + 6 + 6).getMateria().getNome();

                    dtm.setValueAt(nome, i, 2);

                }//fecha for
                for (int i = 0; i < 6; i++) {

                    String nome = horario.get(i + 6 + 6 + 6).getMateria().getNome();

                    dtm.setValueAt(nome, i, 3);

                }//fecha for
                for (int i = 0; i < 6; i++) {

                    String nome = horario.get(i + 6 + 6 + 6 + 6).getMateria().getNome();

                    dtm.setValueAt(nome, i, 4);

                }//fecha for

                jtPeriodos.setModel(dtm);
            }
        } catch (Exception e) {
        }
    }

    private void adicinarAlunoTurma() {
        try {
            AlunoServicos ss = ServicoFactory.getAluno();

            Turma turma = (Turma) JComboTurmas.getSelectedItem();

            if (!(jListTodosOsAlunos.getSelectedIndex() == -1)) {

                ArrayList<Aluno> aluno = new ArrayList<>();

                aluno = (ArrayList<Aluno>) jListTodosOsAlunos.getSelectedValuesList();

                if (aluno != null) {
                    for (int i = 0; i < aluno.size(); i++) {

                        ss.AlterarAluno("aluno set idturma = " + turma.getIdTurma()
                                + " where idaluno = " + aluno.get(i).getIdAluno());
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um aluno");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao adicionar aluno! " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIConfigTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIConfigTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIConfigTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIConfigTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UIConfigTurma dialog = new UIConfigTurma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        dialog.setVisible(false);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JComboTurmas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JList jListAlunos;
    private javax.swing.JList jListTodosOsAlunos;
    private javax.swing.JList jListTurmas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jtFiltrarAluno;
    private javax.swing.JTextField jtFiltrarTurma;
    private javax.swing.JTable jtPeriodos;
    // End of variables declaration//GEN-END:variables
}
